version: "3"

services:
  web:
    image: youngstar.kr.ncr.ntruss.com/youngstar-web:latest
    ports:
      - "80:80"
    links:
      - api
  api:
    image: youngstar.kr.ncr.ntruss.com/youngstar-api:latest
    ports:
      - "4000:4000"
